### PR TITLE
Ci workflow

### PR DESCRIPTION
**Pull request by eva-cosma**
This PR contains the implementation of a basic CI workflow for rust.
In short, when someone pushes or makes a pull request, the following tests are performed:

- `cargo build` succeeds
- All test pass (`cargo test`)
- No formatting issues with rust-fmt
- No issues with clippy

The Makefile has also been updated so that the `ci-runner-github` matches the same tests that are done by the CI Workflow (it wasn't running `cargo test` previously).

Also, here is a sample pull requests that fails: https://github.com/george-cosma/tockloader-rs/pull/1

### CODE REVIEW

**Comment by alexandruradovici** [comment]
As this uses git in the action commands, this might not work with merge queue. I suggest we merge this and try.

**Review by alexandruradovici — DISMISSED** [review]

**Comment by george-cosma** [comment]
For the merge queue to work, it might need the `merge_group`[^1] trigger added, but even then I'm not sure it will work - I can't enable the merge queue on my fork to test. Should I add it, and see if it works?

[^1]: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions

**Review by hudson-ayers — DISMISSED** [review]
Yeah, I figure just give it a shot!

**Comment by george-cosma** [comment]
This change should enable the CI tests to run on the merge queue if the repository is configured correctly.

## A note on settings
For the merge queue to function as expected, it seems that both the "Require merge queue" and "Require status checks to pass before merging" need to both be active at the the same time (Thanks to @alexandruradovici for discovering this). If the second rule is not present, the merge queue will not stop a failing PR from being merged.

I've documented my test attempts over here https://github.com/UPB-CS-OpenSourceUpstream/tockloader-rs/issues/14

**Comment by alexandruradovici** [comment]
Did it run all the tests while in the merge queue?

**Review by alexandruradovici — APPROVED** [review]

**Comment by george-cosma** [comment]
Yes, it ran all of them. 
Here's the link to the test it ran https://github.com/UPB-CS-OpenSourceUpstream/tockloader-rs/actions/runs/4958024994 for PR https://github.com/UPB-CS-OpenSourceUpstream/tockloader-rs/pull/15

**Comment by alexandruradovici** [comment]
As soon as @hudson-ayers approves it, I will merge this manually and enable the merge queue.

**Review by hudson-ayers — APPROVED** [review]
Sorry this slipped through the cracks, but looks good!

**Comment by ppannuto** [comment]
Merged & merge queue enabled on main branch

**Pull request merged**
